server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: vacation-manager
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # 명백하게 명시만 해두면 안전하지만, 없어도 기본값이 SpringPhysicalNamingStrategy
        spring.jpa.hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        jdbc:
          time-zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul   # Jackson (JSON 직렬화/역직렬화)
  mustache:
    enabled: true
    charset: UTF-8
    suffix: .html
    check-template-location: true

logging:
  level:
    p6spy: DEBUG
    com.p6spy.engine.spy: DEBUG

decorator:
  datasource:
    p6spy:
      enable-logging: true

admin:
  username: ${adminUsername}
  password: ${adminPassword}